spring:
  datasource:
    # DruidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # master
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root

      # slaver01
      slaver01:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root

        #权重 默认1 仅read.dataSource.poll.pattern=2时有效
        weight: 1

      # slaver02
      slaver02:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root

        #权重 默认1 仅read.dataSource.poll.pattern=2时有效
        weight: 2

      # druid 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 最大等待超时时间
      max-wait: 30000
      # 检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.springboot.servie.*


      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druiduser
        login-password: druidpwd
        # IP白名单
        # allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true


# mybatis 配置
mybatis-plus:
  # xml文件路径 需要结合 pom <resources>...</resources>
  mapper-locations: classpath:com/example/**/mapper/*.xml
  type-aliases-package: com.example**.model
  configuration:
    # 驼峰
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 返回map时，true:当查询数据为空时字段返回为null；false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 将执行的sql打印出来，这个可以存放在文件中 StdOutImpl的是只能打印到控制台
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 读数据源负载均衡策略 0-随机 1-轮询 2-权重
read:
  dataSource:
    poll:
      pattern: 2
