server:
  port: 8081

spring:
  # shardingJdbc ??????
  shardingsphere:
    datasource:
      #????? ?????????
      names: master,slave0,slave1

      #????
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root

      #?1???
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root

      #?2???
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root

    masterslave:
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave0,slave1
      #?????? round_robin ????
      load-balance-algorithm-type: round_robin

    props:
      sql:
        show: true


# mybatis ??
mybatis-plus:
  # xml???? ???? pom <resources>...</resources>
  mapper-locations: classpath:com/example/**/mapper/*.xml
  type-aliases-package: com.example**.model
  configuration:
    # ??
    map-underscore-to-camel-case: true
    cache-enabled: false
    # ??map??true:?????????????null?false:??????????????????
    call-setters-on-nulls: true
    # ????sql??????????????? StdOutImpl??????????
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl